vim.o.completeopt = "menuone,noselect"
vim.o.cursorline = true
vim.o.expandtab = true
vim.o.hlsearch = false
vim.o.ignorecase = true
-- vim.o.incsearch = true
-- vim.o.list = true
-- vim.o.listchars = "tab:» ,space:·"
vim.o.mouse = "a"
vim.o.number = true
vim.o.relativenumber = true
vim.o.scrolloff = 8
vim.o.shiftwidth = 4
vim.o.signcolumn = "yes"
vim.o.smartcase = true
vim.o.smartindent = true
-- vim.o.softtabstop = 4
vim.o.tabstop = 4
vim.o.termguicolors = true
-- vim.o.timeoutlen = 300
vim.o.undofile = true
vim.o.updatetime = 200
vim.o.wrap = false
